### ISSUE TITLE
How to run it on MacOS

### ISSUE THREAD

**Issue by somenzz** [feschber/lan-mouse#126]
I have executed this：
`brew install libadwaita`
and download the release "lan-mouse-macos-intel"

I chmod u+x on lan-mouse-macos-intel, when run it in terminal, I got "zsh: bad CPU type in executable: /Users/aaron/Desktop/lan-mouse-macos-intel"

**Comment by somenzz** [comment]
My CPU is inter.

**Comment by magicus** [comment]
Are you sure you downloaded the correct file? Can you start a terminal and type `file lan-mouse-macos-intel`? What does that say? Also, what does `uname -a` say?

**Comment by feschber** [comment]
seems like github recently updated their action runners to m1 images by default.
I updated them to use the intel runners again so in about 10 minutes the new prerelease should be working again.

Good catch!

**Comment by feschber** [comment]
should now be the correct intel binary again in the latest prerelease

**Comment by somenzz** [comment]
❯ file lan-mouse-macos-intel
lan-mouse-macos-intel: Mach-O 64-bit executable arm64
I will  download it again, thank you.

**Comment by somenzz** [comment]
But still not work:

❯ ./lan-mouse-macos-intel2 --port 54243
[2024-05-09T02:55:58Z WARN  lan_mouse::config] /Users/aaron/.config/lan-mouse/config.toml: No such file or directory (os error 2)
[2024-05-09T02:55:58Z WARN  lan_mouse::config] Continuing without config file ...
[2024-05-09T02:55:58Z INFO  lan_mouse] release bind: [KeyLeftCtrl, KeyLeftShift, KeyLeftMeta, KeyLeftAlt]
[2024-05-09T02:55:59Z WARN  lan_mouse::config] /Users/aaron/.config/lan-mouse/config.toml: No such file or directory (os error 2)
[2024-05-09T02:55:59Z WARN  lan_mouse::config] Continuing without config file ...
[2024-05-09T02:55:59Z INFO  lan_mouse] release bind: [KeyLeftCtrl, KeyLeftShift, KeyLeftMeta, KeyLeftAlt]
[2024-05-09T02:55:59Z INFO  lan_mouse] Press Ctrl+Alt+Shift+Super to release the mouse
[2024-05-09T02:55:59Z INFO  lan_mouse::server] running service
[2024-05-09T02:55:59Z INFO  lan_mouse::capture] macos input capture not available: not yet implemented
[2024-05-09T02:55:59Z ERROR lan_mouse::capture] falling back to dummy input capture
[2024-05-09T02:55:59Z INFO  lan_mouse::emulate] using macos input emulation
[2024-05-09T02:57:02Z INFO  lan_mouse::server::frontend_task] added client 0
2024-05-09 10:57:05.766 lan-mouse-macos-intel2[18959:2001973] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
[2024-05-09T02:57:14Z INFO  lan_mouse::dns] resolving 10.18.3.66 ...
[2024-05-09T02:57:14Z INFO  lan_mouse::dns] 10.18.3.66: adding ip 10.18.3.66

(<unknown>:18959): Gdk-CRITICAL **: 10:57:14.843: _gdk_macos_surface_update_fullscreen_state: assertion 'GDK_IS_MACOS_SURFACE (self)' failed

(<unknown>:18959): Gdk-CRITICAL **: 10:57:24.538: _gdk_macos_surface_update_fullscreen_state: assertion 'GDK_IS_MACOS_SURFACE (self)' failed

(<unknown>:18959): Gtk-WARNING **: 10:57:24.552: Broken accounting of active state for widget 0x7fddb278afc0(GtkBox)

(<unknown>:18959): Gtk-WARNING **: 10:57:24.552: Broken accounting of active state for widget 0x7fddb278a5b0(GtkBox)

(<unknown>:18959): Gtk-WARNING **: 10:57:24.552: Broken accounting of active state for widget 0x7fddb278a430(AdwComboRow)

**Comment by feschber** [comment]
What dou you mean exactly? Does the window show up?

**Comment by joaomcarlos** [comment]
On Macos cargo also fails (lib adwaita installed via brew):

```
 cargo install lan-mouse
error: process didn't exit successfully: `rustc -vV` (signal: 6, SIGABRT: process abort signal)
--- stderr
dyld[27552]: Symbol not found: __ZN4llvm10PGOOptionsC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES7_S7_S7_NS_18IntrusiveRefCntPtrINS_3vfs10FileSystemEEENS0_9PGOActionENS0_11CSPGOActionEbb
  Referenced from: <5090B140-04BE-3D13-8DD7-B41507163A1B> /usr/local/Cellar/rust/1.77.1/lib/librustc_driver-bd4d02add2e4c5d3.dylib
  Expected in:     <83624E46-48B6-3467-AE49-9DBD1E457F64> /usr/local/Cellar/llvm/18.1.4/lib/libLLVM.dylib

```

**Comment by feschber** [comment]
> On Macos cargo also fails (lib adwaita installed via brew):
> 
> ```
>  cargo install lan-mouse
> error: process didn't exit successfully: `rustc -vV` (signal: 6, SIGABRT: process abort signal)
> --- stderr
> dyld[27552]: Symbol not found: __ZN4llvm10PGOOptionsC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES7_S7_S7_NS_18IntrusiveRefCntPtrINS_3vfs10FileSystemEEENS0_9PGOActionENS0_11CSPGOActionEbb
>   Referenced from: <5090B140-04BE-3D13-8DD7-B41507163A1B> /usr/local/Cellar/rust/1.77.1/lib/librustc_driver-bd4d02add2e4c5d3.dylib
>   Expected in:     <83624E46-48B6-3467-AE49-9DBD1E457F64> /usr/local/Cellar/llvm/18.1.4/lib/libLLVM.dylib
> 
> ```

This seems like an issue with your rust setup. Could you try updating / reinstalling rust and llvm?

**Comment by feschber** [comment]
@joaomcarlos I just tested it again on a fresh VM and it works for me.
LLVM is version 14.0.3 and rust 1.78.

You appear to have llvm 18.1.4 locally installed which might be the cause but I can not say for sure.

**Comment by feschber** [comment]
I will close this, as there is now an official app bundle.
